CadenBookStore/Components/TypesViewComponent.cs
using System;
using System.Linq;
using CadenBookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace CadenBookStore.Components
{
    public class TypesViewComponent: ViewComponent
    {
        private IBookProjectRepository repo { get; set; }

        public TypesViewComponent (IBookProjectRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];


            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);


            return View(types);
        }
    }
}

CadenBookStore/Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="shadow card card-outline-primary m-1 p-1">

    <div class="bg-light p-1">
        <h4>@Model.Title</h4>


        <span class="badge bg-info" style="float: right">
            $ @Model.Price
        </span>
    </div>


    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Category: @Model.Category</li>
        <li>Number of Pages: @Model.PageCount</li>
    </ul>

    <form method="post" asp-page="/AddToCart">


        <input type="hidden" asp-for="@Model.BookId" />
        <!--<input type="hidden" name="returnUrl" value="Needs an at sign ViewContext.HttpContext.Request.PathAndQuery()" />-->

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add To Cart</button>
        </span>

    </form>

</div>

CadenBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!--<link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />-->


</head>

<body>

    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">NILE</span>
        <div style="text-align: right">
            <a class="btn btn-primary" href="/Admin">Log In</a>
        </div>
    </div>




    <div class="row m-1 p-1">

        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>

    </div>

    <footer class="bg-light text-center text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            <p class="text-dark">© 2022 Copyright: Nile</p>
        </div>
        <!-- Copyright -->
    </footer>

</body>
</html>