CadenBookStore/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CadenBookStore.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CadenBookStore.Controllers
{
    public class CheckoutController : Controller
    {
        private IBookCartRepository repo { get; set; }
        private Basket basket { get; set; }

        public CheckoutController(IBookCartRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }


        [HttpGet]
        // GET: /<controller>/
        public IActionResult Checkout()
        {
            return View(new BookCart());
        }


        [HttpPost]
        public IActionResult Checkout(BookCart bookcart)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your basket is empty!");

            }

            if (ModelState.IsValid)
            {
                bookcart.Lines = basket.Items.ToArray();
                repo.SaveBook(bookcart);
                basket.ClearBasket();

                return RedirectToPage("/CheckoutComplete"); ;
            }
            else
            {
                return View();
            }
        }
    }
}

CadenBookStore/Pages/AddToCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CadenBookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CadenBookStore.Models.Infrastructure;


namespace CadenBookStore.Pages
{
    public class AddToCartModel : PageModel
    {
        private IBookProjectRepository repo { get; set; }

        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }


        public AddToCartModel (IBookProjectRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }




        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);


            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

CadenBookStore/Pages/AddToCart.cshtml
@page
@model CadenBookStore.Pages.AddToCartModel
@{
}

<h1>Your Basket</h1>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>$25.00</td>
                <td>$@((i.Quantity * 25).ToString("#,##0.00"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total: </td>
            <td>$@Model.basket.CalculateTotal().ToString("#,##0.00")</td>
        </tr>
    </tfoot>

</table>


<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Back to Shopping</a>
    <a class="btn btn-primary" asp-controller="Checkout" asp-action="Checkout">Checkout</a>
</div>

CadenBookStore/Pages/CheckoutComplete.cshtml
@page

@{
}


<div class="text-center">
    <h2>Thanks for shopping with us.</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

CadenBookStore/Pages/_AddToCartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>

    <div class="bg-dark text-white p-2">
        Caden's Boook store
    </div>


    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>